source 'https://rubygems.org'

gem 'sinatra'
gem 'rspec'
gem 'rack-test'
gem 'arduino_firmata'
gem 'coveralls'
gem 'rake'
gem 'webmock'
gem 'httparty'
gem 'sinatra-logger'
gem 'foreman'
gem 'foreman_debian', github: 'cargomedia/foreman-debian'
gem 'thin'
gem 'mandrill-api'
gem 'dotenv'
